export { default as Home } from './Home';
export { default as Learning } from './Learning';
export { default as Account } from './Account';
export { default as Leaderboard } from './Leaderboard';
export { default as Information } from './Information';
export { default as Menu } from './Menu';
export { default as LoginPage } from './LoginPage';
export { default as Review } from './Review';
export { default as TestPage } from './TestPage';
